// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: message/request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Message.Request {

  /// <summary>Holder for reflection information generated from message/request.proto</summary>
  public static partial class RequestReflection {

    #region Descriptor
    /// <summary>File descriptor for message/request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVtZXNzYWdlL3JlcXVlc3QucHJvdG8SD21lc3NhZ2UucmVxdWVzdBoSbWVz",
            "c2FnZS9jb3JlLnByb3RvItwBCgdSZXF1ZXN0EgoKAklkGAEgASgNEioKB1Nl",
            "c3Npb24YAiABKAsyGS5tZXNzYWdlLmNvcmUuVXVpZE1lc3NhZ2USLAoJQ2hh",
            "cmFjdGVyGAMgASgLMhkubWVzc2FnZS5jb3JlLlV1aWRNZXNzYWdlEi4KCE1v",
            "dmVtZW50GAQgASgOMhoubWVzc2FnZS5yZXF1ZXN0LkRpcmVjdGlvbkgAEiwK",
            "BkZhY2luZxgFIAEoDjIaLm1lc3NhZ2UucmVxdWVzdC5EaXJlY3Rpb25IAEIN",
            "CgtSZXF1ZXN0RGF0YSp7CglEaXJlY3Rpb24SCAoETm9uZRAAEgkKBU5vcnRo",
            "EAESDQoJTm9ydGhFYXN0EAMSCAoERWFzdBACEg0KCVNvdXRoRWFzdBAGEgkK",
            "BVNvdXRoEAQSDQoJU291dGhXZXN0EAwSCAoEV2VzdBAIEg0KCU5vcnRoV2Vz",
            "dBAJQgJIAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Message.Core.CoreReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Message.Request.Direction), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Message.Request.Request), global::Message.Request.Request.Parser, new[]{ "Id", "Session", "Character", "Movement", "Facing" }, new[]{ "RequestData" }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Direction {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("North")] North = 1,
    [pbr::OriginalName("NorthEast")] NorthEast = 3,
    [pbr::OriginalName("East")] East = 2,
    [pbr::OriginalName("SouthEast")] SouthEast = 6,
    [pbr::OriginalName("South")] South = 4,
    [pbr::OriginalName("SouthWest")] SouthWest = 12,
    [pbr::OriginalName("West")] West = 8,
    [pbr::OriginalName("NorthWest")] NorthWest = 9,
  }

  #endregion

  #region Messages
  public sealed partial class Request : pb::IMessage<Request> {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Message.Request.RequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request(Request other) : this() {
      id_ = other.id_;
      session_ = other.session_ != null ? other.session_.Clone() : null;
      character_ = other.character_ != null ? other.character_.Clone() : null;
      switch (other.RequestDataCase) {
        case RequestDataOneofCase.Movement:
          Movement = other.Movement;
          break;
        case RequestDataOneofCase.Facing:
          Facing = other.Facing;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private uint id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "Session" field.</summary>
    public const int SessionFieldNumber = 2;
    private global::Message.Core.UuidMessage session_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.Core.UuidMessage Session {
      get { return session_; }
      set {
        session_ = value;
      }
    }

    /// <summary>Field number for the "Character" field.</summary>
    public const int CharacterFieldNumber = 3;
    private global::Message.Core.UuidMessage character_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.Core.UuidMessage Character {
      get { return character_; }
      set {
        character_ = value;
      }
    }

    /// <summary>Field number for the "Movement" field.</summary>
    public const int MovementFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.Request.Direction Movement {
      get { return requestDataCase_ == RequestDataOneofCase.Movement ? (global::Message.Request.Direction) requestData_ : 0; }
      set {
        requestData_ = value;
        requestDataCase_ = RequestDataOneofCase.Movement;
      }
    }

    /// <summary>Field number for the "Facing" field.</summary>
    public const int FacingFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.Request.Direction Facing {
      get { return requestDataCase_ == RequestDataOneofCase.Facing ? (global::Message.Request.Direction) requestData_ : 0; }
      set {
        requestData_ = value;
        requestDataCase_ = RequestDataOneofCase.Facing;
      }
    }

    private object requestData_;
    /// <summary>Enum of possible cases for the "RequestData" oneof.</summary>
    public enum RequestDataOneofCase {
      None = 0,
      Movement = 4,
      Facing = 5,
    }
    private RequestDataOneofCase requestDataCase_ = RequestDataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestDataOneofCase RequestDataCase {
      get { return requestDataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearRequestData() {
      requestDataCase_ = RequestDataOneofCase.None;
      requestData_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(Session, other.Session)) return false;
      if (!object.Equals(Character, other.Character)) return false;
      if (Movement != other.Movement) return false;
      if (Facing != other.Facing) return false;
      if (RequestDataCase != other.RequestDataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (session_ != null) hash ^= Session.GetHashCode();
      if (character_ != null) hash ^= Character.GetHashCode();
      if (requestDataCase_ == RequestDataOneofCase.Movement) hash ^= Movement.GetHashCode();
      if (requestDataCase_ == RequestDataOneofCase.Facing) hash ^= Facing.GetHashCode();
      hash ^= (int) requestDataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Id);
      }
      if (session_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Session);
      }
      if (character_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Character);
      }
      if (requestDataCase_ == RequestDataOneofCase.Movement) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Movement);
      }
      if (requestDataCase_ == RequestDataOneofCase.Facing) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Facing);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
      }
      if (session_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Session);
      }
      if (character_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Character);
      }
      if (requestDataCase_ == RequestDataOneofCase.Movement) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Movement);
      }
      if (requestDataCase_ == RequestDataOneofCase.Facing) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Facing);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.session_ != null) {
        if (session_ == null) {
          Session = new global::Message.Core.UuidMessage();
        }
        Session.MergeFrom(other.Session);
      }
      if (other.character_ != null) {
        if (character_ == null) {
          Character = new global::Message.Core.UuidMessage();
        }
        Character.MergeFrom(other.Character);
      }
      switch (other.RequestDataCase) {
        case RequestDataOneofCase.Movement:
          Movement = other.Movement;
          break;
        case RequestDataOneofCase.Facing:
          Facing = other.Facing;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt32();
            break;
          }
          case 18: {
            if (session_ == null) {
              Session = new global::Message.Core.UuidMessage();
            }
            input.ReadMessage(Session);
            break;
          }
          case 26: {
            if (character_ == null) {
              Character = new global::Message.Core.UuidMessage();
            }
            input.ReadMessage(Character);
            break;
          }
          case 32: {
            requestData_ = input.ReadEnum();
            requestDataCase_ = RequestDataOneofCase.Movement;
            break;
          }
          case 40: {
            requestData_ = input.ReadEnum();
            requestDataCase_ = RequestDataOneofCase.Facing;
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
